# Chp-12: Numpy Arrays


![](title_pict/numpy_arrays.png)

## Motivation
Let's attempt to multiply each element of a list by 10.
- The `*` operator repeats the list elements.
- If we use the `*` operator on a list, instead of multiplying each element by 10, it replicates the initial list 10 times, as shown in the following code:

In [9]:
list1 = [1,2,3]
print(list1*10)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


- We can multiply each element of a list using list comprehensions.

In [10]:
new_list = [i*10 for i in list1]
print(new_list)

[10, 20, 30]


- However, it's quite common to multiply each element of a sequence by a fixed number, and there should be a more efficient way to accomplish this.
- NumPy arrays interpret the `*` operator as multiplication, not repetition.

In [13]:
import numpy as np
array1 = np.array([1,2,3])
print(array1)

[1 2 3]


In [14]:
print(array1*10)

[10 20 30]


There's a similar situation with the + operator.
- For lists, + concatenates elements, whereas for NumPy arrays, it performs componentwise addition.

In [15]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [16]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1+array2)

[5 7 9]


![](pict/logo_numpy.jpeg)

## Numpy 
[Numpy](https://numpy.org/) is the foundational package for scientific computing in Python.
- Numpy's primary data structure is arrays.
    - Arrays are known for their speed and versatility.
    - They enable vectorized operations.
    - Indexing facilitates accessing values within an array.
- NumPy offers a comprehensive collection of mathematical tools for various computations, encompassing:
    - Matrix operations
    - Generation of random numbers
    - Mathematical and statistical functions
- NumPy methods can be used for importing and manipulating images.
- NumPy is the foundation for powerful machine learning libraries like scikit-learn and SciPy.
- It's customary to import the `numpy` package under the alias `np` for brevity and clarity in code.

In [1]:
import numpy as np

## Numpy Arrays
A NumPy array, also known as `ndarray`, is a multidimensional array.
- You can perform mathematical and statistical operations on arrays.
- Manipulations such as reshaping, sorting, stacking, transposing, and shuffling arrays are possible.

The `np.array()` method is used to create an array. The following code generates a 2 by 3 matrix.

In [2]:
myarray = np.array([ [1,2,3], [4,5,6]])
print(myarray)

[[1 2 3]
 [4 5 6]]


The type of a NumPy array is `ndarray`.

In [3]:
print(type(myarray))

<class 'numpy.ndarray'>
